// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/bigtablelite.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BigTableLite_Set_FullMethodName    = "/bigtablelite.BigTableLite/Set"
	BigTableLite_Get_FullMethodName    = "/bigtablelite.BigTableLite/Get"
	BigTableLite_Delete_FullMethodName = "/bigtablelite.BigTableLite/Delete"
)

// BigTableLiteClient is the client API for BigTableLite service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BigTableLite service definition
type BigTableLiteClient interface {
	// Set a key-value pair
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	// Get a value by key
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Delete a key value pair
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type bigTableLiteClient struct {
	cc grpc.ClientConnInterface
}

func NewBigTableLiteClient(cc grpc.ClientConnInterface) BigTableLiteClient {
	return &bigTableLiteClient{cc}
}

func (c *bigTableLiteClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, BigTableLite_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bigTableLiteClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, BigTableLite_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bigTableLiteClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, BigTableLite_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BigTableLiteServer is the server API for BigTableLite service.
// All implementations must embed UnimplementedBigTableLiteServer
// for forward compatibility.
//
// BigTableLite service definition
type BigTableLiteServer interface {
	// Set a key-value pair
	Set(context.Context, *SetRequest) (*SetResponse, error)
	// Get a value by key
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Delete a key value pair
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedBigTableLiteServer()
}

// UnimplementedBigTableLiteServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBigTableLiteServer struct{}

func (UnimplementedBigTableLiteServer) Set(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedBigTableLiteServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedBigTableLiteServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBigTableLiteServer) mustEmbedUnimplementedBigTableLiteServer() {}
func (UnimplementedBigTableLiteServer) testEmbeddedByValue()                      {}

// UnsafeBigTableLiteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BigTableLiteServer will
// result in compilation errors.
type UnsafeBigTableLiteServer interface {
	mustEmbedUnimplementedBigTableLiteServer()
}

func RegisterBigTableLiteServer(s grpc.ServiceRegistrar, srv BigTableLiteServer) {
	// If the following call pancis, it indicates UnimplementedBigTableLiteServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BigTableLite_ServiceDesc, srv)
}

func _BigTableLite_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BigTableLiteServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BigTableLite_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BigTableLiteServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BigTableLite_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BigTableLiteServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BigTableLite_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BigTableLiteServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BigTableLite_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BigTableLiteServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BigTableLite_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BigTableLiteServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BigTableLite_ServiceDesc is the grpc.ServiceDesc for BigTableLite service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BigTableLite_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bigtablelite.BigTableLite",
	HandlerType: (*BigTableLiteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _BigTableLite_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _BigTableLite_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BigTableLite_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bigtablelite.proto",
}
